version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.40
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s ~/project/src/
      - run:
          name: "Test Website"
          command: |
            echo "Ignoring for now since theme is old and needs to be redone."
            #htmlproofer ~/project/src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - add_ssh_keys
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo 'sweb0.revidian.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHyIA/VJN9GHUeYUvauk+sGsQcvk8FpXErixwvgqQmW1pdje/Vo4RyAAskzdgoR+HUYOWM1gLW7ZFZHL8F//sqw=' >> ~/.ssh/known_hosts
              rsync -va --delete src/public/ root@sweb0.revidian.net:/static-websites/cloud-unpacked/linodians/public_html
            fi
